import { NextRequest, NextResponse } from "next/server";
import { store } from "@/lib/store";
import { generateId } from "@/lib/utils";

export const dynamic = "force-dynamic";

/**
 * Seller API - Permite a vendedores crear licencias mediante URL
 * 
 * Ejemplo de uso:
 * /api/seller/?sellerkey=abc123&type=add&app_id=APP_ID&expiry=30&amount=5&level=1&format=json
 * 
 * Parámetros:
 * - sellerkey (requerido): Clave del vendedor
 * - type (requerido): Tipo de operación (add, info, balance)
 * - app_id (requerido para 'add'): ID de la aplicación
 * - expiry: Días de duración (default: 30)
 * - amount: Cantidad de licencias a generar (default: 1)
 * - level: Nivel de acceso (default: 1)
 * - mask: Formato de la key (default: ****-****-****-****)
 * - format: Formato de respuesta (json, text) (default: json)
 */

export async function GET(req: NextRequest) {
  try {
    const url = new URL(req.url);
    
    // Obtener parámetros
    const sellerKey = url.searchParams.get("sellerkey");
    const type = url.searchParams.get("type") || "info";
    const appId = url.searchParams.get("app_id");
    const expiry = parseInt(url.searchParams.get("expiry") || "30");
    const amount = parseInt(url.searchParams.get("amount") || "1");
    const level = parseInt(url.searchParams.get("level") || "1");
    const mask = url.searchParams.get("mask") || "****-****-****-****";
    const format = url.searchParams.get("format") || "json";

    // Validar seller key
    if (!sellerKey) {
      return sendResponse(format, false, "seller_key es requerido");
    }

    // Buscar vendedor por key
    const seller = await store.getSellerByKey(sellerKey);
    
    if (!seller) {
      return sendResponse(format, false, "Seller key inválido");
    }

    if (seller.status !== "active") {
      return sendResponse(format, false, "Seller account inactivo");
    }

    // Procesar según tipo
    switch (type) {
      case "add":
        return await handleAddLicenses(seller, appId, expiry, amount, level, mask, format);
      
      case "adduser":
        const username = url.searchParams.get("username");
        const password = url.searchParams.get("password");
        const subscription = url.searchParams.get("subscription") || "Basic";
        return await handleAddUser(seller, appId, username, password, expiry, subscription, format);
      
      case "info":
        return sendResponse(format, true, "Seller info", {
          seller_id: seller.id,
          username: seller.username,
          credits: seller.credits,
          status: seller.status,
        });
      
      case "balance":
        return sendResponse(format, true, "Balance retrieved", {
          credits: seller.unlimited_credits ? "∞" : seller.credits,
          unlimited: seller.unlimited_credits,
        });
      
      default:
        return sendResponse(format, false, "Tipo inválido. Use: add, adduser, info, balance");
    }

  } catch (error: any) {
    console.error("Seller API error:", error);
    return sendResponse("json", false, error.message || "Error del servidor");
  }
}

async function handleAddLicenses(
  seller: any,
  appId: string | null,
  expiry: number,
  amount: number,
  level: number,
  mask: string,
  format: string
) {
  // Validar app_id
  if (!appId) {
    return sendResponse(format, false, "app_id es requerido");
  }

  // Validar que la app existe
  const app = await store.getAppById(appId);
  if (!app) {
    return sendResponse(format, false, "App no encontrada");
  }

  // Verificar créditos (si no es ilimitado)
  if (!seller.unlimited_credits) {
    const costPerLicense = 1; // 1 crédito por licencia
    const totalCost = amount * costPerLicense;
    
    if (seller.credits < totalCost) {
      return sendResponse(format, false, `Créditos insuficientes. Necesitas ${totalCost}, tienes ${seller.credits}`);
    }
  }

  // Validar límites
  if (amount < 1 || amount > 1000) {
    return sendResponse(format, false, "Amount debe estar entre 1 y 1000");
  }

  if (expiry < 1 || expiry > 3650) {
    return sendResponse(format, false, "Expiry debe estar entre 1 y 3650 días");
  }

  // Generar licencias
  const licenses = [];
  const now = new Date();
  const expiresAt = new Date(now.getTime() + expiry * 86400000);

  for (let i = 0; i < amount; i++) {
    const key = generateLicenseKey(mask);
    
    licenses.push({
      app_id: appId,
      key,
      duration_days: expiry,
      level,
      uses: 0,
      max_uses: 999999,
      hwid_lock: false,
      ip_lock: false,
      status: "active",
      used_by: null,
      activated_at: null,
      expires_at: expiresAt.toISOString(),
      created_by: seller.id,
      note: `Generated by seller: ${seller.username}`,
    });
  }

  // Insertar licencias
  const created = await store.createLicenses(licenses);

  // Descontar créditos (si no es ilimitado)
  if (!seller.unlimited_credits) {
    const newCredits = seller.credits - amount;
    await store.updateSeller(seller.id, { credits: newCredits });
  }

  // Respuesta
  const keys = created.map((l: any) => l.key);
  
  return sendResponse(format, true, `${amount} licencia(s) creada(s)`, {
    licenses: keys,
    count: keys.length,
    expiry_days: expiry,
    level,
    expires_at: expiresAt.toISOString(),
  });
}

async function handleAddUser(
  seller: any,
  appId: string | null,
  username: string | null,
  password: string | null,
  expiry: number,
  subscription: string,
  format: string
) {
  // Validar parámetros
  if (!appId) {
    return sendResponse(format, false, "app_id es requerido");
  }

  if (!username) {
    return sendResponse(format, false, "username es requerido");
  }

  if (!password) {
    return sendResponse(format, false, "password es requerido");
  }

  // Validar que la app existe y pertenece al seller
  const app = await store.getAppById(appId);
  if (!app) {
    return sendResponse(format, false, "App no encontrada");
  }

  if (app.seller_id !== seller.id) {
    return sendResponse(format, false, "No tienes permiso para crear usuarios en esta app");
  }

  // Verificar créditos (si no es ilimitado) - 1 crédito por usuario
  if (!seller.unlimited_credits) {
    if (seller.credits < 1) {
      return sendResponse(format, false, `Créditos insuficientes. Necesitas 1 crédito, tienes ${seller.credits}`);
    }
  }

  // Validar expiry
  if (expiry < 1 || expiry > 3650) {
    return sendResponse(format, false, "Expiry debe estar entre 1 y 3650 días");
  }

  // Verificar si el usuario ya existe
  const existingUsers = await store.listAppUsers({ appId });
  const userExists = existingUsers.some((u: any) => u.username.toLowerCase() === username.toLowerCase());
  
  if (userExists) {
    return sendResponse(format, false, `El usuario '${username}' ya existe`);
  }

  // Calcular fecha de expiración
  const now = new Date();
  const expiresAt = new Date(now.getTime() + expiry * 86400000);

  // Crear usuario
  const newUser = {
    app_id: appId,
    username,
    password_hash: password, // En producción debería hashearse
    email: `${username}@generated.local`,
    subscription_level: subscription,
    subscription_expires_at: expiresAt.toISOString(),
    hwid: null,
    ip: null,
    last_login: null,
    created_by: seller.id,
  };

  const createdUser = await store.createAppUser(newUser);

  // Descontar créditos (si no es ilimitado)
  if (!seller.unlimited_credits) {
    const newCredits = seller.credits - 1;
    await store.updateSeller(seller.id, { credits: newCredits });
  }

  // Respuesta
  return sendResponse(format, true, "Usuario creado exitosamente", {
    user: {
      id: createdUser.id,
      username: createdUser.username,
      password,
      subscription: subscription,
      expiry_days: expiry,
      expires_at: expiresAt.toISOString(),
      app_id: appId,
    },
  });
}

function generateLicenseKey(mask: string): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  
  return mask
    .split("")
    .map((char) => {
      if (char === "*") {
        return chars[Math.floor(Math.random() * chars.length)];
      }
      return char;
    })
    .join("");
}

function sendResponse(format: string, success: boolean, message: string, data?: any) {
  if (format === "text") {
    // Formato texto plano
    if (success && data?.licenses) {
      const text = data.licenses.join("\n");
      return new NextResponse(text, {
        status: 200,
        headers: { "Content-Type": "text/plain" },
      });
    }
    
    return new NextResponse(message, {
      status: success ? 200 : 400,
      headers: { "Content-Type": "text/plain" },
    });
  }

  // Formato JSON (default)
  return NextResponse.json(
    {
      success,
      message,
      data: data || null,
    },
    { status: success ? 200 : 400 }
  );
}
