import { NextRequest, NextResponse } from "next/server";
import { store } from "@/lib/store";
import { generateId } from "@/lib/utils";

// GET - List licenses for seller's apps
export async function GET(req: NextRequest) {
  try {
    const sellerSession = req.cookies.get("seller_session")?.value;
    if (!sellerSession) {
      return NextResponse.json(
        { success: false, message: "No autorizado" },
        { status: 401 }
      );
    }

    const seller = await store.getSellerById(sellerSession);
    if (!seller) {
      return NextResponse.json(
        { success: false, message: "Sesión inválida" },
        { status: 401 }
      );
    }

    const url = new URL(req.url);
    const appId = url.searchParams.get("app_id");

    if (!appId) {
      return NextResponse.json(
        { success: false, message: "app_id es requerido" },
        { status: 400 }
      );
    }

    // Verify the app belongs to this seller
    const app = await store.getAppById(appId);
    if (!app || app.seller_id !== seller.id) {
      return NextResponse.json(
        { success: false, message: "App no autorizada" },
        { status: 403 }
      );
    }

    const licenses = await store.listLicenses({ appId, limit: 500 });

    return NextResponse.json({
      success: true,
      data: licenses,
    });
  } catch (error: any) {
    console.error("Error listing licenses:", error);
    return NextResponse.json(
      { success: false, message: error.message },
      { status: 500 }
    );
  }
}

// POST - Create licenses
export async function POST(req: NextRequest) {
  try {
    const sellerSession = req.cookies.get("seller_session")?.value;
    if (!sellerSession) {
      return NextResponse.json(
        { success: false, message: "No autorizado" },
        { status: 401 }
      );
    }

    const seller = await store.getSellerById(sellerSession);
    if (!seller) {
      return NextResponse.json(
        { success: false, message: "Sesión inválida" },
        { status: 401 }
      );
    }

    const body = await req.json();
    const { app_id, amount, expiry, level } = body;

    if (!app_id || !amount || !expiry) {
      return NextResponse.json(
        { success: false, message: "Faltan campos requeridos" },
        { status: 400 }
      );
    }

    // Verify the app belongs to this seller
    const app = await store.getAppById(app_id);
    if (!app || app.seller_id !== seller.id) {
      return NextResponse.json(
        { success: false, message: "App no autorizada" },
        { status: 403 }
      );
    }

    // Check credits
    const amountNum = parseInt(amount);
    if (!seller.unlimited_credits && seller.credits < amountNum) {
      return NextResponse.json(
        { success: false, message: `Créditos insuficientes. Necesitas ${amountNum}, tienes ${seller.credits}` },
        { status: 403 }
      );
    }

    // Generate licenses
    const licenses = [];
    const now = new Date();
    const expiresAt = new Date(now.getTime() + parseInt(expiry) * 86400000);

    for (let i = 0; i < amountNum; i++) {
      const key = generateLicenseKey();
      
      licenses.push({
        app_id,
        key,
        duration_days: parseInt(expiry),
        level: parseInt(level) || 1,
        uses: 0,
        max_uses: 999999,
        hwid_lock: false,
        ip_lock: false,
        status: "unused",
        used_by: null,
        activated_at: null,
        expires_at: expiresAt.toISOString(),
        created_by: seller.id,
        note: `Generated by seller: ${seller.username}`,
      });
    }

    const created = await store.createLicenses(licenses);

    // Deduct credits
    if (!seller.unlimited_credits) {
      await store.updateSeller(seller.id, { credits: seller.credits - amountNum });
    }

    return NextResponse.json({
      success: true,
      data: created,
      message: `${amountNum} licencia(s) creada(s)`,
    });
  } catch (error: any) {
    console.error("Error creating licenses:", error);
    return NextResponse.json(
      { success: false, message: error.message },
      { status: 500 }
    );
  }
}

function generateLicenseKey(): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  const segments = [4, 4, 4, 4];
  
  return segments
    .map((length) => {
      let segment = "";
      for (let i = 0; i < length; i++) {
        segment += chars[Math.floor(Math.random() * chars.length)];
      }
      return segment;
    })
    .join("-");
}
